In [103]:
import pandas as pd
import numpy as np

from sklearn.model_selection import KFold

# hyperparameters
splits = 6 # kfold nested cross-validation
stepSize = 5 # sensor placement in every 5 days
lastKDays = 30 # we forget data before k days
contextDays = 30 # we start with these many days.
assert (contextDays <= lastKDays)

# hyperparameters - will be defined by the regressor chosen



srcname = '../../data/beijingb_scaled.csv'
df = pd.read_csv(srcname)
df = df[df.columns[1:]]
times = df['ts'].unique()
times.sort()
totalDays = len(times)
X_cols = list(df.columns)
X_cols.remove('PM2.5')
y_col = ['PM2.5']

In [104]:
X_cols

['latitude',
 'longitude',
 'ts',
 'temperature',
 'pressure',
 'humidity',
 'WSX',
 'WSY',
 'weather',
 'station_id']

In [105]:
y_col

['PM2.5']

In [55]:
df = pd.read_csv

In [56]:
df.shape

(12542, 12)

In [57]:
df = df[df.columns[1:]]
df.head()

,latitude,longitude,ts,temperature,pressure,humidity,WSX,WSY,weather,PM2.5,station_id
0,0.58292,0.17557,0.000000,0.718851,0.653601,0.521719,0.587483,0.417198,0.0,156.250000,1001.0
1,0.58292,0.17557,0.002747,0.622896,0.738081,0.231674,0.348570,0.672356,0.0,24.833333,1001.0
2,0.58292,0.17557,0.005495,0.628654,0.706512,0.271946,0.477721,0.503845,0.0,72.583333,1001.0
3,0.58292,0.17557,0.008242,0.556687,0.758978,0.122624,0.335436,0.687828,0.0,30.043478,1001.0
4,0.58292,0.17557,0.010989,0.573000,0.757200,0.169683,0.624696,0.445893,0.0,23.083333,1001.0

In [100]:
from sklearn.model_selection import KFold
X = df
splits = 6

stepSize = 5 # sensor placement in every 5 days
lastKDays = 30 # we forget data before k days
contextDays = lastKDays # we start with these many days.


kfout = KFold(n_splits=splits, random_state=0)
kfin = KFold(n_splits=splits - 1, random_state=0)

times = df['ts'].unique()
times.sort()
totalDays = len(times)

allStations = df['station_id'].unique()
allStations.sort()

for sts_ftrain_index, sts_test_index in kfout.split(allStations):
    for sts_train_index, sts_val_index in kfin.split(sts_ftrain_index):
        
        # getting the correct stations
        sts_test = allStations[sts_test_index]
        sts_val = allStations[sts_ftrain_index[sts_val_index]]
        sts_train = allStations[sts_ftrain_index[sts_train_index]]
        
#         plotting for checking if things are correct
#         plt.scatter(sts_test, [1]*len(sts_test), c='r', alpha=.6)
#         plt.scatter(sts_val, [1]*len(sts_val), c='b', alpha=.6)
#         plt.scatter(sts_train, [1]*len(sts_train), c='c', alpha=.6)
#         plt.show()
        
        # getting the train, test, val sets
        test_df = df[df['station_id'].isin(sts_test)]
        val_df = df[df['station_id'].isin(sts_val)]
        train_df = df[df['station_id'].isin(sts_train)]
        
#         # checking if there is some intersection, should not be
#         print(np.intersect1d(test_df['station_id'].unique(), val_df['station_id'].unique()))
#         print(np.intersect1d(train_df['station_id'].unique(), val_df['station_id'].unique()))
#         print(np.intersect1d(train_df['station_id'].unique(), test_df['station_id'].unique()))
        
        # getting the temporally relevant data
        for time_ix in range(contextDays-1, totalDays, stepSize): # zero index
            # data before today
            temporal_train_df = train_df[train_df['ts'] <= times[time_ix]]
            temporal_val_df = val_df[val_df['ts'] <= times[time_ix]] # TODO
            temporal_test_df = test_df[test_df['ts'] == times[time_ix]]
            
            # data after contextDays - lastKDays
            temporal_train_df = temporal_train_df[temporal_train_df['ts'] >= times[time_ix - lastKDays + 1]]
            temporal_val_df = temporal_val_df[temporal_val_df['ts'] >= times[time_ix - lastKDays + 1]]
            
#             # if incrementing as expected len == 30, 30, 1
#             yo = []
#             yo.append(len(temporal_train_df['ts'].unique()))
#             yo.append(len(temporal_val_df['ts'].unique()))
#             yo.append(len(temporal_test_df['ts'].unique()))
#             try:
#                 assert(yo == [30, 30, 1])
#             except:
#                 print("# of Time Stamp checking")
#                 print (yo)
            
#             # if incrementing as expected len == 24, 6, 6
#             yo = []
#             yo.append(len(temporal_train_df['station_id'].unique()))
#             yo.append(len(temporal_val_df['station_id'].unique()))
#             yo.append(len(temporal_test_df['station_id'].unique()))
#             try:
#                 assert(yo == [24, 6, 6])
#             except:
#                 print("# of Stations checking")
#                 print (yo)

###########Deal with the weird data we might have using Deepak's code#################


#             for 
            
            
#             for hy in hyperparams: # hy is a dictionary

In [110]:
d = {}
for i in range(10):
    d[i] = {}
    for j in range(11):
        d[i][j] = {}
        for k in "APORB":
            d[i][j][k] = 'afds'

In [112]:
pd.DataFrame(d)

0    {'A': 'afds', 'P': 'afds', 'O': 'afds', 'R': '...
1    {'A': 'afds', 'P': 'afds', 'O': 'afds', 'R': '...
2    {'A': 'afds', 'P': 'afds', 'O': 'afds', 'R': '...
3    {'A': 'afds', 'P': 'afds', 'O': 'afds', 'R': '...
4    {'A': 'afds', 'P': 'afds', 'O': 'afds', 'R': '...
5    {'A': 'afds', 'P': 'afds', 'O': 'afds', 'R': '...
6    {'A': 'afds', 'P': 'afds', 'O': 'afds', 'R': '...
7    {'A': 'afds', 'P': 'afds', 'O': 'afds', 'R': '...
8    {'A': 'afds', 'P': 'afds', 'O': 'afds', 'R': '...
9    {'A': 'afds', 'P': 'afds', 'O': 'afds', 'R': '...
Name: 0, dtype: object

In [52]:
X_train

,latitude,longitude,ts,temperature,pressure,humidity,WSX,WSY,weather,PM2.5,station_id
0,0.582920,0.175570,0.000000,0.718851,0.653601,0.521719,0.587483,0.417198,0.0000,156.250000,1001.0
1,0.582920,0.175570,0.002747,0.622896,0.738081,0.231674,0.348570,0.672356,0.0000,24.833333,1001.0
2,0.582920,0.175570,0.005495,0.628654,0.706512,0.271946,0.477721,0.503845,0.0000,72.583333,1001.0
3,0.582920,0.175570,0.008242,0.556687,0.758978,0.122624,0.335436,0.687828,0.0000,30.043478,1001.0
4,0.582920,0.175570,0.010989,0.573000,0.757200,0.169683,0.624696,0.445893,0.0000,23.083333,1001.0
...,...,...,...,...,...,...,...,...,...,...,...
8357,0.196118,0.706446,0.027473,0.523896,0.637827,0.865060,0.651983,0.555840,0.3125,26.041667,1034.0
8358,0.196118,0.706446,0.030220,0.702539,0.567344,0.569683,0.452704,0.270068,0.0000,43.291667,1034.0
8359,0.196118,0.706446,0.032967,0.810009,0.560674,0.285520,0.475532,0.523818,0.0000,101.833333,1034.0
8360,0.196118,0.706446,0.035714,0.714054,0.612251,0.144796,0.304791,0.721587,0.0000,41.750000,1034.0
8361,0.196118,0.706446,0.038462,0.750517,0.563787,0.225792,0.703812,0.413822,0.0000,78.300000,1034.0

In [40]:
X_test

,latitude,longitude,ts,temperature,pressure,humidity,WSX,WSY,weather,PM2.5,station_id
10452,0.636364,0.982578,1.000000,0.772812,0.689790,0.579874,0.653506,0.393669,0.0625,127.590909,1026.0
10453,0.592441,1.000000,0.000000,0.702539,0.658048,0.591855,0.573098,0.450113,0.0000,108.500000,1033.0
10454,0.592441,1.000000,0.002747,0.589312,0.732300,0.338462,0.325430,0.674044,0.0000,22.791667,1033.0
10455,0.592441,1.000000,0.005495,0.607544,0.706067,0.384163,0.490542,0.513972,0.0000,49.590909,1033.0
10456,0.592441,1.000000,0.008242,0.522143,0.749196,0.218552,0.324179,0.704989,0.0000,28.708333,1033.0
...,...,...,...,...,...,...,...,...,...,...,...
12537,0.863126,0.013938,0.989011,0.714638,0.122369,0.268719,0.646526,0.411119,0.0000,62.695652,1031.0
12538,0.863126,0.013938,0.991758,0.703465,0.067949,0.526298,0.648995,0.416376,0.5000,93.956522,1031.0
12539,0.863126,0.013938,0.994505,0.647982,0.125131,0.611441,0.659039,0.425160,0.2500,45.272727,1031.0
12540,0.863126,0.013938,0.997253,0.686611,0.144948,0.602715,0.666721,0.410837,0.0000,114.125000,1031.0
12541,0.863126,0.013938,1.000000,0.717241,0.126081,0.624729,0.674172,0.415278,0.0625,128.909091,1031.0