In [1]:
import pandas as pd

In [2]:
temp = []
for reg in ['las', 'knn', 'xgb', 'xgbRF', 'svr', 'gpST', "gpFULL"]:
    try:
        odf = pd.read_csv(f"../exp1/src/results/beijingb_scaled/{reg}/final_test.csv")        
        new_temp = odf[odf["is_val_error"] == False]
        lastKDayss = new_temp['lastKDays'].unique()
        for lastKDays in lastKDayss:
            temp.append(new_temp[(new_temp['lastKDays'] == lastKDays) & (new_temp['time_ix'] >= lastKDays - 1)])
    except Exception as e:
        print(e)
        pass
df = pd.concat(temp)
df = df[~(df['reg'] == "SVGP") & ~(df['lastKDays'].isin([1, 100, 200]))]
df = df.rename(columns={"reg": "Method"})

[Errno 2] File b'../exp1/src/results/beijingb_scaled/xgbRF/final_test.csv' does not exist: b'../exp1/src/results/beijingb_scaled/xgbRF/final_test.csv'
[Errno 2] File b'../exp1/src/results/beijingb_scaled/gpST/final_test.csv' does not exist: b'../exp1/src/results/beijingb_scaled/gpST/final_test.csv'

In [3]:
df.groupby("Method").get_group('XGBRegressor').groupby('lastKDays').get_group(30)['hy_ix'].unique()

array([ 0, 10,  4,  6, 12,  5,  3, 11,  9,  8])

In [10]:
df.groupby("Method").get_group("XGBRegressor").groupby(["lastKDays", "hy_ix", "time_ix"]).mean()

                         is_val_error  stepSize  kout  kin       rmse  \
lastKDays hy_ix time_ix
10        0     29              False       2.0  1.75 -1.0  12.937152
                31              False       2.0  4.50 -1.0  10.889287
                33              False       2.0  1.75 -1.0   5.739590
                35              False       2.0  2.00 -1.0   7.032208
                37              False       2.0  2.75 -1.0   4.601358
...                               ...       ...   ...  ...        ...
50        12    265             False       2.0  3.00 -1.0  40.336595
                275             False       2.0  1.00 -1.0  20.671244
                287             False       2.0  3.00 -1.0  27.325205
                349             False       2.0  4.00 -1.0  41.279945
                357             False       2.0  1.00 -1.0  35.032974

                               mae
lastKDays hy_ix time_ix
10        0     29        9.564972
                31        6.198824
                33        4.341842
                35        5.456015
                37        3.634185
...                            ...
50        12    265      29.508008
                275      15.691464
                287      21.261135
                349      35.215305
                357      17.405680

[1881 rows x 6 columns]

In [23]:
t = df.groupby("Method").get_group("XGBRegressor").groupby(["lastKDays"]).get_group(30)
v = t.groupby(["time_ix","hy_ix"]).mean()
# , "hy_ix", "time_ix"]).mean()

In [65]:
 a = []

In [90]:
d = {}

In [91]:
for ix, temp_df in t.groupby(["time_ix", "kout"]):
    idx = temp_df["hy_ix"].values.item()
    d[idx] = d.get(idx, 0) + 1

In [92]:
d

{0: 313, 10: 275, 12: 26, 4: 288, 5: 18, 6: 19, 11: 25, 3: 12, 9: 12, 8: 2}

In [52]:
v

               is_val_error  stepSize  lastKDays      kout  kin       rmse  \
time_ix hy_ix
29      0             False       2.0       30.0  2.000000 -1.0  14.476093
        10            False       2.0       30.0  3.500000 -1.0  13.165225
31      0             False       2.0       30.0  1.500000 -1.0   6.551462
        4             False       2.0       30.0  2.000000 -1.0   9.400507
        10            False       2.0       30.0  5.000000 -1.0  12.765240
...                     ...       ...        ...       ...  ...        ...
355     6             False       2.0       30.0  3.000000 -1.0  11.193496
        10            False       2.0       30.0  1.666667 -1.0   5.937116
357     0             False       2.0       30.0  5.000000 -1.0  17.272490
        4             False       2.0       30.0  3.000000 -1.0  16.846842
        10            False       2.0       30.0  1.333333 -1.0  10.240270

                     mae
time_ix hy_ix
29      0       9.653144
        10      9.845453
31      0       5.564733
        4       6.602557
        10      7.586004
...                  ...
355     6       7.468345
        10      4.628064
357     0      14.625179
        4      13.908159
        10      8.334732

[471 rows x 7 columns]

In [57]:
d={}

In [58]:
for i in range(29,358,2):
    t1 = v.loc[i]["rmse"].idxmax()
    if t1 not in d:
        d[t1] = 1
    else:
        d[t1] = d[t1] + 1
    if t1==3:
        print(v.loc[i]["rmse"])
#     breakv.loc[31]

hy_ix
0    7.425791
3    9.045956
4    5.336260
Name: rmse, dtype: float64

In [53]:
d

{0: 39, 10: 39, 12: 4, 4: 63, 5: 7, 6: 3, 11: 9, 3: 1}

In [32]:
v.loc[31].idxmin(axis = 0)

TypeError: reduction operation 'argmin' not allowed for this dtype

In [55]:
df.groupby("Method").get_group("XGBRegressor").groupby(["lastKDays", "hy_ix"]).mean()

                 is_val_error  stepSize      kout  kin     time_ix       rmse  \
lastKDays hy_ix
10        0             False       2.0  2.543590 -1.0  179.430769  18.366470
          1             False       2.0  1.000000 -1.0  161.000000  10.267835
          2             False       2.0  1.750000 -1.0  225.000000  12.664443
          3             False       2.0  2.909091 -1.0  227.363636   9.868492
          4             False       2.0  2.374486 -1.0  203.962963  15.657841
          5             False       2.0  3.285714 -1.0  197.380952  19.933031
          6             False       2.0  2.566667 -1.0  206.600000  23.106676
          8             False       2.0  3.000000 -1.0  289.000000  12.533625
          9             False       2.0  1.500000 -1.0  250.000000   5.755640
          10            False       2.0  2.454545 -1.0  199.398268  15.943287
          11            False       2.0  2.545455 -1.0  187.909091  13.237184
          12            False       2.0  2.739130 -1.0  198.826087  13.502028
20        0             False       2.0  2.393293 -1.0  175.500000  19.481093
          3             False       2.0  2.352941 -1.0  226.176471   7.917803
          4             False       2.0  2.455479 -1.0  197.760274  17.035931
          5             False       2.0  2.304348 -1.0  200.565217  19.044486
          6             False       2.0  2.350000 -1.0  194.600000  17.766444
          9             False       2.0  2.300000 -1.0  252.200000   7.852710
          10            False       2.0  2.759036 -1.0  204.269076  14.532248
          11            False       2.0  2.260870 -1.0  181.260870  14.898569
          12            False       2.0  2.535714 -1.0  209.142857  16.725533
30        0             False       2.0  2.421725 -1.0  173.006390  19.127795
          3             False       2.0  2.500000 -1.0  242.666667   5.801624
          4             False       2.0  2.586806 -1.0  195.638889  16.827723
          5             False       2.0  2.388889 -1.0  197.111111  16.747459
          6             False       2.0  3.157895 -1.0  195.210526  14.471462
          8             False       2.0  3.000000 -1.0  262.000000   9.658265
          9             False       2.0  2.416667 -1.0  264.833333   9.082053
          10            False       2.0  2.458182 -1.0  207.152727  15.983628
          11            False       2.0  2.600000 -1.0  202.600000  16.317044
          12            False       2.0  2.423077 -1.0  179.692308  11.571698
50        0             False       2.0  2.355856 -1.0  183.729730  20.971479
          2             False       2.0  3.000000 -1.0  303.000000   4.707263
          3             False       2.0  2.190476 -1.0  265.095238  11.015056
          4             False       2.0  2.477419 -1.0  212.206452  17.185065
          5             False       2.0  1.882353 -1.0  162.411765  14.658106
          6             False       2.0  2.791667 -1.0  179.083333  19.891968
          8             False       2.0  1.500000 -1.0  198.000000   9.378086
          9             False       2.0  1.142857 -1.0  192.714286   5.553177
          10            False       2.0  2.611307 -1.0  208.611307  16.373379
          11            False       2.0  3.368421 -1.0  216.578947  15.796476
          12            False       2.0  3.000000 -1.0  183.000000  20.044173

                       mae
lastKDays hy_ix
10        0      14.355465
          1       8.306629
          2      10.602317
          3       7.053604
          4      11.808423
          5      15.471093
          6      18.067411
          8      11.863498
          9       4.752161
          10     12.383357
          11     11.014805
          12     11.674517
20        0      15.383711
          3       6.324056
          4      12.849250
          5      15.819191
          6      13.379996
          9       5.860209
          10     11.107580
          11     11.630798
          12     13.689317
30        0      15.266031
          3       4.731330
          4      12.671878
          5      13.568790
          6      11.638423
          8       9.122837
          9       7.554585
          10     12.140072
          11     12.736142
          12      9.227975
50        0      16.667473
          2       4.486895
          3       7.054773
          4      13.118847
          5      12.114024
          6      16.258710
          8       9.250144
          9       4.711440
          10     12.577017
          11     11.670209
          12     15.349377

In [5]:
df.groupby("Method").get_group("KNeighborsRegressor").groupby(["lastKDays", "hy_ix"]).mean()

                 is_val_error  stepSize      kout  kin     time_ix       rmse  \
lastKDays hy_ix
10        0             False       2.0  2.592593 -1.0  207.148148  26.288169
          1             False       2.0  2.579378 -1.0  195.202946  20.074194
          2             False       2.0  2.369128 -1.0  193.147651  20.280464
          3             False       2.0  2.328571 -1.0  189.485714  21.618263
          4             False       2.0  2.369565 -1.0  184.086957  23.649627
          5             False       2.0  2.576923 -1.0  174.692308  21.583432
          6             False       2.0  2.133333 -1.0  141.800000  20.065190
          7             False       2.0  2.200000 -1.0  180.000000  21.045513
          8             False       2.0  2.187500 -1.0  224.250000  17.583910
          9             False       2.0  2.400000 -1.0  182.000000  22.532739
20        0             False       2.0  3.000000 -1.0  175.956522  26.482160
          1             False       2.0  2.561983 -1.0  192.775207  21.803356
          2             False       2.0  2.236111 -1.0  206.569444  20.088563
          3             False       2.0  2.303030 -1.0  181.090909  25.155460
          4             False       2.0  2.500000 -1.0  199.480000  19.929896
          5             False       2.0  3.375000 -1.0  208.416667  19.756508
          6             False       2.0  2.333333 -1.0  197.222222  27.504632
          7             False       2.0  1.857143 -1.0  149.857143  16.909651
          8             False       2.0  2.000000 -1.0  181.625000  18.364399
          9             False       2.0  2.533333 -1.0  172.200000  17.245085
30        0             False       2.0  3.210526 -1.0  214.473684  30.427057
          1             False       2.0  2.524207 -1.0  195.203673  22.119569
          2             False       2.0  2.325926 -1.0  204.362963  20.632762
          3             False       2.0  2.492754 -1.0  187.811594  23.432044
          4             False       2.0  2.466667 -1.0  207.488889  22.728508
          5             False       2.0  2.888889 -1.0  174.888889  18.841949
          6             False       2.0  1.950000 -1.0  144.700000  18.532843
          7             False       2.0  2.210526 -1.0  165.736842  16.576589
          8             False       2.0  2.500000 -1.0  165.181818  14.401405
          9             False       2.0  2.500000 -1.0  161.923077  21.317243
50        0             False       2.0  2.826087 -1.0  202.913043  24.389935
          1             False       2.0  2.517361 -1.0  206.430556  22.410079
          2             False       2.0  2.488372 -1.0  211.201550  23.238417
          3             False       2.0  2.196429 -1.0  185.607143  25.072116
          4             False       2.0  2.823529 -1.0  181.705882  20.016650
          5             False       2.0  2.531250 -1.0  201.000000  19.802906
          6             False       2.0  2.352941 -1.0  193.823529  24.227690
          7             False       2.0  2.750000 -1.0  192.833333  16.792795
          8             False       2.0  2.200000 -1.0  186.400000  18.330932
          9             False       2.0  2.292683 -1.0  182.853659  17.469023

                       mae
lastKDays hy_ix
10        0      21.379587
          1      15.567491
          2      15.707880
          3      16.285910
          4      17.765349
          5      16.912612
          6      14.779108
          7      17.530372
          8      13.618233
          9      18.187491
20        0      21.286018
          1      16.630936
          2      15.431083
          3      19.253748
          4      15.392973
          5      15.283737
          6      22.771962
          7      13.759206
          8      15.236810
          9      14.591302
30        0      24.199285
          1      16.863405
          2      15.968958
          3      18.041897
          4      17.729787
          5      15.502954
          6      14.721003
          7      13.228923
          8      11.935694
          9      17.971768
50        0      19.420461
          1      17.161171
          2      18.218956
          3      18.914731
          4      15.394505
          5      15.973039
          6      18.263706
          7      13.794872
          8      15.549424
          9      14.312305