In [58]:
import pandas as pd

In [59]:
temp = []
for reg in ['las', 'knn', 'xgb', 'xgbRF', 'svr', "gpFULL", "gpST"]:
    try:
        odf = pd.read_csv(f"../exp1/src/results/beijingb_scaled/{reg}/final.csv")
        new_temp = odf[odf["is_val_error"] == True]
        lastKDayss = new_temp['lastKDays'].unique()
        for lastKDays in lastKDayss:
            temp.append(new_temp[(new_temp['lastKDays'] == lastKDays) & (new_temp['time_ix'] >= lastKDays - 1)])
    except FileNotFoundError:
        pass
df = pd.concat(temp)
# df = df.append(interpols)
# df = df[~(df['reg'] == "SVGP") & ~(df['lastKDays'].isin([100, 200]))]
# df = df.rename(columns={"reg": "Method"})
# emptydf = create_good_df(df)
# emptydf

# # plt.figure(figsize=(12, 8))
# # sns.barplot(data=df, x = "lastKDays", y="rmse", hue="Method", errwidth=0)
# # plt.ylabel("RMSE")
# # plt.xlabel("Number of days used as context")
# # plt.title(f"Average Test Performances Using Nested Cross Validation on Beijing B.")

In [60]:
df

,is_val_error,reg,stepSize,lastKDays,kout,kin,time_ix,hy_ix,rmse,mae
80,True,Lasso,2,50,0,0,49,0,21.996528,21.212389
81,True,Lasso,2,50,0,0,49,1,21.205709,12.919581
82,True,Lasso,2,50,0,0,49,2,19.634375,12.513431
83,True,Lasso,2,50,0,0,49,3,13.113262,11.202593
84,True,Lasso,2,50,0,0,49,4,21.996528,21.212389
...,...,...,...,...,...,...,...,...,...,...
182818,True,SVR,2,10,5,4,357,1,214.593178,214.369253
182819,True,SVR,2,10,5,4,357,2,212.518365,212.284377
182820,True,SVR,2,10,5,4,357,3,192.546917,192.185030
182821,True,SVR,2,10,5,4,357,4,23.360056,21.024251
182822,True,SVR,2,10,5,4,357,5,26.277407,24.411498

In [ ]:
stepSize = 2

In [62]:
df["reg"].unique()

array(['Lasso', 'KNeighborsRegressor', 'XGBRegressor', 'SVR'],
      dtype=object)

In [63]:
tempdf3

,is_val_error,reg,stepSize,lastKDays,kout,kin,time_ix,hy_ix,rmse,mae
250850,True,KNeighborsRegressor,2,10,0,0,29,0,24.792396,16.268072
250851,True,KNeighborsRegressor,2,10,0,0,29,1,26.450635,15.349798
250852,True,KNeighborsRegressor,2,10,0,0,29,2,23.494201,14.747850
250853,True,KNeighborsRegressor,2,10,0,0,29,3,22.190595,15.798586
250854,True,KNeighborsRegressor,2,10,0,0,29,4,20.297351,15.395329
...,...,...,...,...,...,...,...,...,...,...
259055,True,KNeighborsRegressor,2,10,0,4,357,5,15.283383,11.358727
259056,True,KNeighborsRegressor,2,10,0,4,357,6,14.937587,11.674592
259057,True,KNeighborsRegressor,2,10,0,4,357,7,14.625331,11.074576
259058,True,KNeighborsRegressor,2,10,0,4,357,8,15.113647,11.955625
259059,True,KNeighborsRegressor,2,10,0,4,357,9,14.472742,11.796508

In [64]:
tempdf3.groupby(["hy_ix"]).mean()

,is_val_error,stepSize,lastKDays,kout,kin,time_ix,rmse,mae
hy_ix,,,,,,,,
0,True,2.0,10.0,0.0,2.009744,193.492083,26.423241,20.545008
1,True,2.0,10.0,0.0,2.009744,193.492083,21.686944,16.463736
2,True,2.0,10.0,0.0,2.009744,193.492083,23.197480,17.904986
3,True,2.0,10.0,0.0,2.009744,193.492083,24.105055,18.856551
4,True,2.0,10.0,0.0,2.009744,193.492083,24.930604,19.728953
5,True,2.0,10.0,0.0,2.009744,193.492083,25.643215,20.472221
6,True,2.0,10.0,0.0,2.009744,193.492083,26.355408,21.235242
7,True,2.0,10.0,0.0,2.009744,193.492083,26.958211,21.885084
8,True,2.0,10.0,0.0,2.009744,193.492083,27.541198,22.484063
9,True,2.0,10.0,0.0,2.009744,193.492083,28.118050,23.096862

In [65]:
best_hy_ix

1

In [41]:
tempdf3

,is_val_error,reg,stepSize,lastKDays,kout,kin,time_ix,hy_ix,rmse,mae
152490,True,SVR,2,10,0,0,29,0,181.410499,180.927046
152491,True,SVR,2,10,0,0,29,1,181.374775,180.891714
152492,True,SVR,2,10,0,0,29,2,178.772527,178.334183
152493,True,SVR,2,10,0,0,29,3,43.133265,42.132584
152494,True,SVR,2,10,0,0,29,4,60.693201,40.242717
...,...,...,...,...,...,...,...,...,...,...
157411,True,SVR,2,10,0,4,357,1,210.234300,209.948394
157412,True,SVR,2,10,0,4,357,2,208.605579,208.305559
157413,True,SVR,2,10,0,4,357,3,192.069514,191.615914
157414,True,SVR,2,10,0,4,357,4,21.862128,16.647103
157415,True,SVR,2,10,0,4,357,5,25.095127,18.989114

In [57]:
val_err_df = tempdf3
splits = 6

In [20]:
hyperparameters = [{}]
alphas = [0.001, 0.01, 0.1, 1, 10, 100, 1000]
for alpha in (alphas):
    hy = { 'alpha': alpha }
    hyperparameters.append(hy)

In [21]:
val_err_df = tempdf3
splits = 6

tempstore = val_err_df.loc[0:0].copy()
tempstore.drop(index=tempstore.index, inplace=True) # getting an empty df with correct dtypes
assert (tempstore.shape[0] == 0)

for kInSelect in range(splits - 1):
    tempdf2 = val_err_df[val_err_df['kin'] == kInSelect]
    for hy_ix in range(len(hyperparameters)):
        tempdf3 = tempdf2[tempdf2["hy_ix"] == hy_ix]
        rmse_val, mae_val = tempdf3[['rmse', 'mae']].mean().copy()
        tempstore.loc[tempstore.shape[0]] = tempdf3.loc[tempdf3.index[0]].copy() # randomly add
        # editing the last row added,
        # no side effects as tempdf3 would never be used again
        # print (tempstore)
        tempstore.loc[tempstore.shape[0] - 1][['rmse', 'mae', 'time_ix']] = rmse_val, mae_val, -1
        # print ("SHOULD BE A EMPTY") # it is, append copies
        # print (outdf[outdf['rmse'] == rmse_val])
        # time_ix is not relevant
    
assert tempstore.shape[0] == (splits-1) * len(hyperparameters)

# print ('Reduced on dimension essentially.')


# this for nested cross validation. the way we choose the best hyperparameters
# for the second experiment will be cleared later.
# TODO Discuss this with deepak.
# tempstore now contains mean rmse (across time_stamps)
# we now choose the best_hy_ix for a perticular kout. i.e.
# we will only have `splits` number of best_hy_ix

# TODO Need to assure that len(hyperparameters) >= num of splits
ix = tempstore['rmse'].idxmin()
best_hy_ix = tempstore.loc[ix]["hy_ix"]
hy = hyperparameters[best_hy_ix]

/home/apoorv/Desktop/github/.env/lib/python3.6/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/apoorv/Desktop/github/.env/lib/python3.6/site-packages/pandas/core/series.py:1298: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_labels(key, value)

In [22]:
tempstore

,is_val_error,reg,stepSize,lastKDays,kout,kin,time_ix,hy_ix,rmse,mae
0,True,KNeighborsRegressor,2,10,0,0,29,0,24.792396,16.268072
1,True,KNeighborsRegressor,2,10,0,0,29,1,26.450635,15.349798
2,True,KNeighborsRegressor,2,10,0,0,29,2,23.494201,14.747850
3,True,KNeighborsRegressor,2,10,0,0,29,3,22.190595,15.798586
4,True,KNeighborsRegressor,2,10,0,0,29,4,20.297351,15.395329
5,True,KNeighborsRegressor,2,10,0,0,29,5,17.552151,14.084798
6,True,KNeighborsRegressor,2,10,0,0,29,6,19.914973,14.915924
7,True,KNeighborsRegressor,2,10,0,0,29,7,20.039619,14.757492
8,True,KNeighborsRegressor,2,10,0,1,29,0,10.688617,8.532246
9,True,KNeighborsRegressor,2,10,0,1,29,1,5.794224,5.438140
10,True,KNeighborsRegressor,2,10,0,1,29,2,9.836460,7.490461
11,True,KNeighborsRegressor,2,10,0,1,29,3,15.503582,10.818746
12,True,KNeighborsRegressor,2,10,0,1,29,4,15.703376,11.280411
13,True,KNeighborsRegressor,2,10,0,1,29,5,12.927126,9.127248
14,True,KNeighborsRegressor,2,10,0,1,29,6,12.311700,8.423679
15,True,KNeighborsRegressor,2,10,0,1,29,7,9.989050,7.496018
16,True,KNeighborsRegressor,2,10,0,2,29,0,26.271223,19.151851
17,True,KNeighborsRegressor,2,10,0,2,29,1,22.314638,14.993822
18,True,KNeighborsRegressor,2,10,0,2,29,2,25.214951,17.622775
19,True,KNeighborsRegressor,2,10,0,2,29,3,26.148539,18.356723
20,True,KNeighborsRegressor,2,10,0,2,29,4,24.870401,17.943150
21,True,KNeighborsRegressor,2,10,0,2,29,5,26.082796,18.663644
22,True,KNeighborsRegressor,2,10,0,2,29,6,26.877561,19.115572
23,True,KNeighborsRegressor,2,10,0,2,29,7,25.235172,17.121121
24,True,KNeighborsRegressor,2,10,0,3,29,0,7.233236,5.330504
25,True,KNeighborsRegressor,2,10,0,3,29,1,9.557859,7.787993
26,True,KNeighborsRegressor,2,10,0,3,29,2,8.065842,6.370740
27,True,KNeighborsRegressor,2,10,0,3,29,3,9.843194,7.631676
28,True,KNeighborsRegressor,2,10,0,3,29,4,13.088362,9.253934
29,True,KNeighborsRegressor,2,10,0,3,29,5,13.543996,9.736110
30,True,KNeighborsRegressor,2,10,0,3,29,6,12.127845,9.409406
31,True,KNeighborsRegressor,2,10,0,3,29,7,12.875919,10.350815
32,True,KNeighborsRegressor,2,10,0,4,29,0,10.978167,8.674879
33,True,KNeighborsRegressor,2,10,0,4,29,1,7.244847,5.610321
34,True,KNeighborsRegressor,2,10,0,4,29,2,6.271131,5.318177
35,True,KNeighborsRegressor,2,10,0,4,29,3,7.282922,5.742639
36,True,KNeighborsRegressor,2,10,0,4,29,4,8.895800,7.108981
37,True,KNeighborsRegressor,2,10,0,4,29,5,7.335109,6.103651
38,True,KNeighborsRegressor,2,10,0,4,29,6,9.172240,6.939823
39,True,KNeighborsRegressor,2,10,0,4,29,7,8.956164,6.249253

In [55]:
val_err_df.loc[val_err_df.index[0]]

is_val_error            True
reg             XGBRegressor
stepSize                   2
lastKDays                200
kout                       0
kin                        0
time_ix                  199
hy_ix                      0
rmse                 71.8068
mae                  64.4018
Name: 195825, dtype: object

In [26]:
import os
import sys
import time
import argparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold

from sklearn.linear_model import Lasso
from sklearn.neighbors import KNeighborsRegressor
import xgboost
def setRegHy(reg):
    '''Sets relevant hyperparameters and regressor, based on the args passed'''
    hyperparameters = [{}] # first use the default hyperparams :)

    if reg == 'svr':
        from sklearn.svm import SVR
        Regressor = SVR
        hyperparameters = [] # SVR cries when we pass empty params
        C = [10**i for i in [-3, -2, 0, 1, 3, 5]]

        for c in C:
            hy = {
               'C': c,
               'gamma': 'auto'
            }
            hyperparameters.append(hy)

    elif reg == 'knn':
        Regressor = KNeighborsRegressor
        n_neighbors = [i for i in range(3, 20, 2)]
        weights=['distance']#, 'uniform'] # essentially idw
        for n in n_neighbors:
            for w in weights:
                hy = {
                    'n_neighbors': n,
                    'weights': w
                }
                hyperparameters.append(hy)

    elif reg == 'las':
        Regressor = Lasso
        alphas = [0.001, 0.01, 0.1, 1, 10, 100, 1000]
        for alpha in (alphas):
            hy = { 'alpha': alpha }
            hyperparameters.append(hy)

    elif reg == 'xgb':
        Regressor = xgboost.XGBRegressor
        # hyperparameters given to be searched by Deepak
        depths = [10, 50]
        lrs = [0.01, 0.1, 1]
        estimators = [10, 50]
        for depth in depths:
            for lr in lrs:
                for estimator in estimators:
                    hy = {
                        'max_depth': depth,
                        'learning_rate': lr,
                        'n_estimators': estimator,
            'n_jobs': -1,
                    }
                    hyperparameters.append(hy)

    elif reg == 'xgbRF':
        Regressor = xgboost.XGBRFRegressor
        # hyperparameters given to be searched by Deepak
        depths = [10, 50]
        lrs = [0.01, 0.1, 1]
        estimators = [10, 50]
        for depth in depths:
            for lr in lrs:
                for estimator in estimators:
                    hy = {
                        'max_depth': depth,
                        'learning_rate': lr,
                        'n_estimators': estimator,
            'n_jobs': -1,
                    }
                    hyperparameters.append(hy)

    elif reg in ['gpST', 'gpFULL']:
        Regressor = gpflow.models.GPR
        config = tf.ConfigProto()
        config.gpu_options.allow_growth=True
        sess = tf.Session(config=config)

    else:
        raise ValueError("We need a predefined Regressor, for sane hyperparameters")
    return (Regressor, hyperparameters)